all: arr_sum_recursive.c simple_stack.c simple_stack_var.c reverse_arr.c float_data_idx.c float_data_ptr.c sort_even_odd.c move_right.c
	gcc -Wall -Wextra -Wpedantic -g -o arr_sum_recursive -std=c11 arr_sum_recursive.c
	gcc -Wall -Wextra -Wpedantic -g -o simple_stack -std=c11 simple_stack.c
	gcc -Wall -Wextra -Wpedantic -g -o simple_stack_var -std=c11 simple_stack_var.c
	gcc -Wall -Wextra -Wpedantic -g -o reverse_arr -std=c11 reverse_arr.c
	gcc -Wall -Wextra -Wpedantic -g -o float_data_idx -std=c11 float_data_idx.c
	gcc -Wall -Wextra -Wpedantic -g -o float_data_ptr -std=c11 float_data_ptr.c
	gcc -Wall -Wextra -Wpedantic -g -o sort_even_odd -std=c11 sort_even_odd.c
	gcc -Wall -Wextra -Wpedantic -g -o move_right -std=c11 move_right.c

arr_sum_recursive: arr_sum_recursive.c
	gcc -Wall -Wextra -Wpedantic -g -o arr_sum_recursive -std=c11 arr_sum_recursive.c

simple_stack: simple_stack.c
	gcc -Wall -Wextra -Wpedantic -g -o simple_stack -std=c11 simple_stack.c

simple_stack_var: simple_stack_var.c
	gcc -Wall -Wextra -Wpedantic -g -o simple_stack_var -std=c11 simple_stack_var.c

reverse_arr: reverse_arr.c
	gcc -Wall -Wextra -Wpedantic -g -o reverse_arr -std=c11 reverse_arr.c

float_data_idx: float_data_idx.c
	gcc -Wall -Wextra -Wpedantic -g -o float_data_idx -std=c11 float_data_idx.c -lm

float_data_ptr: float_data_ptr.c
	gcc -Wall -Wextra -Wpedantic -g -o float_data_ptr -std=c11 float_data_ptr.c -lm

sort_even_odd: sort_even_odd.c
	gcc -Wall -Wextra -Wpedantic -g -o sort_even_odd -std=c11 sort_even_odd.c

move_right: move_right.c
	gcc -Wall -Wextra -Wpedantic -g -o move_right -std=c11 move_right.c

clean:
	rm arr_sum_recursive simple_stack simple_stack_var reverse_arr float_data_ptr float_data_idx sort_even_odd move_right
