CC = gcc
CFLAGS = -Wall -Wextra -Wpedantic -g

all: 1 2 3 4

1: 1.c
	$(CC) $(CFLAGS)-o 1 -std=c11 1.c

2: 2.c
	$(CC) $(CFLAGS)-o 2 -std=c11 2.c

3: 3.c
	$(CC) $(CFLAGS)-o 3 -std=c11 3.c -lm

4: 4.c
	$(CC) $(CFLAGS)-o 4 -std=c11 4.c
